<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <VintageStory Condition="'$(CI)' == 'true'">$(RUNNER_TEMP)/vintagestory</VintageStory>
    <VintageStory Condition="'$(VintageStory)' == ''">$(VINTAGE_STORY)</VintageStory>
    <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
  </PropertyGroup>

  <Target Name="RemoveSymbolsFromPublish" AfterTargets="ComputeFilesToPublish">
    <ItemGroup Condition="'$(Configuration)' == 'Release'">
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)"
        Condition="'%(ResolvedFileToPublish.Filename)%(ResolvedFileToPublish.Extension)' == '$(AssemblyName).deps.json'" />
    </ItemGroup>
  </Target>
</Project>
