<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <TargetVintageStory Condition="'$(CI)' == 'true'">1.22.0</TargetVintageStory>
    <VintageStoryPath Condition="'$(CI)' == 'true'">$(RUNNER_TEMP)/vintagestory</VintageStoryPath>
    <VintageStoryPath Condition="'$(VintageStoryPath)' == ''">$(VINTAGE_STORY)</VintageStoryPath>
  </PropertyGroup>
</Project>
